Repository mattermost/mattermost-data-warehouse, pull requests merged in 2023-04, with the labels that each got.

#1225 Update version_release_dates.csv
  transform/snowflake-dbt/seeds/version_release_dates.csv
Labels: 3: Reviews Complete

#1258 Changing cadence for dbt models hourly runs
  transform/snowflake-dbt/dbt_project.yml
  transform/snowflake-dbt/models/events/nightly/calls_events.sql
  transform/snowflake-dbt/models/events/nightly/cloud_pageview_events.sql
  transform/snowflake-dbt/models/events/nightly/cloud_portal_pageview_events.sql
  transform/snowflake-dbt/models/events/nightly/feature_flag_telemetry.sql
  transform/snowflake-dbt/models/events/nightly/focalboard_event_telemetry.sql
  transform/snowflake-dbt/models/events/nightly/incident_response_events.sql
  transform/snowflake-dbt/models/events/nightly/mobile_events.sql
  transform/snowflake-dbt/models/events/nightly/performance_events.sql
  transform/snowflake-dbt/models/events/nightly/plugin_events.sql
  transform/snowflake-dbt/models/events/nightly/portal_events.sql
  transform/snowflake-dbt/models/events/nightly/rudder_webapp_events.sql
  transform/snowflake-dbt/models/events/nightly/security.sql
  transform/snowflake-dbt/models/events/nightly/segment_mobile_events.sql
  transform/snowflake-dbt/models/events/nightly/segment_webapp_events.sql
  transform/snowflake-dbt/models/events/nightly/user_events_by_date.sql
  transform/snowflake-dbt/models/events/nightly/user_events_telemetry.sql
  transform/snowflake-dbt/models/focalboard/focalboard_activity.sql
  transform/snowflake-dbt/models/focalboard/focalboard_blocks.sql
  transform/snowflake-dbt/models/focalboard/focalboard_config.sql
  transform/snowflake-dbt/models/focalboard/focalboard_fact.sql
  transform/snowflake-dbt/models/focalboard/focalboard_server.sql
  transform/snowflake-dbt/models/focalboard/focalboard_workspaces.sql
  transform/snowflake-dbt/models/incident_collaboration/incident_collaboration_fact.sql
  transform/snowflake-dbt/models/incident_collaboration/incident_daily_details.sql
  transform/snowflake-dbt/models/mattermost/hourly/user_28day_retention.sql
  transform/snowflake-dbt/models/mattermost/nightly/focalboard_user_retention.sql
  transform/snowflake-dbt/models/mattermost/nightly/nps_data.sql
  transform/snowflake-dbt/models/mattermost/nightly/nps_server_daily_score.sql
  transform/snowflake-dbt/models/mattermost/nightly/nps_server_version_daily_score.sql
  transform/snowflake-dbt/models/mattermost/nightly/nps_user_daily_score.sql
  transform/snowflake-dbt/models/mattermost/nightly/user_retention.sql
  transform/snowflake-dbt/models/qa/events_mobile_telemetry.sql
  transform/snowflake-dbt/models/qa/events_web_desktop_telemetry.sql
  transform/snowflake-dbt/models/qa/incident_response_telemetry.sql
  transform/snowflake-dbt/models/qa/plugins_telemetry.sql
  transform/snowflake-dbt/models/qa/server_telemetry.sql
Labels: Work In Progress

#1257 MM-51085: add source and staging models for commonly used Salesforce data
  transform/mattermost-analytics/models/staging/salesforce/_salesforce__docs.md
  transform/mattermost-analytics/models/staging/salesforce/_salesforce__models.yml
  transform/mattermost-analytics/models/staging/salesforce/_salesforce__sources.yml
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__campaign.sql
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__campaign_member.sql
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__contact.sql
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__lead.sql
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__opportunity.sql
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__opportunity_line_item.sql
  transform/mattermost-analytics/models/staging/salesforce/stg_salesforce__user.sql
Labels: 2: Dev Review
