Repository mattermost/mattermost-data-warehouse, pull requests merged in 2023-08, with the labels that each got.

#1329 MM-48421: server activity metrics
  transform/mattermost-analytics/models/intermediate/product/servers/_latest_daily/int_activity_latest_daily.sql
  transform/mattermost-analytics/models/intermediate/product/servers/_latest_daily/int_activity_legacy_latest_daily.sql
  transform/mattermost-analytics/models/intermediate/product/servers/int_server_activity_spined.sql
  transform/mattermost-analytics/models/marts/product/_product__models.yml
  transform/mattermost-analytics/models/marts/product/fct_active_users.sql
  transform/mattermost-analytics/models/staging/mattermost2/_mattermost2__models.yml
  transform/mattermost-analytics/models/staging/mattermost2/stg_mattermost2__activity.sql
  transform/mattermost-analytics/models/staging/mm_telemetry_prod/_mm_telemetry_prod__models.yml
  transform/mattermost-analytics/models/staging/mm_telemetry_prod/stg_mm_telemetry_prod__activity.sql
Labels: Do Not Merge, Work In Progress

#1326 Update version_release_dates.csv
  transform/snowflake-dbt/seeds/version_release_dates.csv
Labels: 3: Reviews Complete

#1318 MM-51472 Create model to sync Newsletter data to SFDC (via hightouch)
  transform/mattermost-analytics/dbt_project.yml
  transform/mattermost-analytics/models/marts/marketing/_marketing__models.yml
  transform/mattermost-analytics/models/marts/marketing/fct_security_newsletter.sql
  transform/mattermost-analytics/models/staging/cws/_cws__models.yml
  transform/mattermost-analytics/models/staging/cws/stg_cws__marketing.sql
Labels: 2: Dev Review
