Repository mattermost/mattermost-data-warehouse, pull requests merged in 2024-05, with the labels that each got.

#1500 Hotfix: remove channel actions
  transform/mattermost-analytics/seeds/features/playbook_events.csv
  transform/mattermost-analytics/tests/staging/incident_response_prod/test_tracks__all_actions_are_known.sql
Labels: 2: Dev Review

#1506 Hotfix: fix duplicates in active user base report
  transform/mattermost-analytics/models/intermediate/data_eng/geoip/int_ip_country_lookup.sql
  transform/mattermost-analytics/models/reports/product/active_user_base/_active_user_base___models.yml
Labels: 2: Dev Review

#1507 MM-58201: add more fields for installation information
  transform/mattermost-analytics/models/marts/product/_product__models.yml
  transform/mattermost-analytics/models/marts/product/dim_daily_server_config.sql
  transform/mattermost-analytics/models/reports/product/active_user_base/_active_user_base___models.yml
  transform/mattermost-analytics/models/reports/product/active_user_base/rpt_active_user_base.sql
Labels: Do Not Merge, Work In Progress

#1509 Add subscription history model
  transform/mattermost-analytics/models/marts/sales/_sales__models.yml
  transform/mattermost-analytics/models/marts/sales/fct_subscription_history.sql
  transform/mattermost-analytics/models/staging/cws/_cws__models.yml
  transform/mattermost-analytics/models/staging/cws/_cws__sources.yml
  transform/mattermost-analytics/models/staging/cws/stg_cws__subscription_history.sql
Labels: 3: Reviews Complete

#1499 Update version_release_dates.csv
  transform/snowflake-dbt/seeds/version_release_dates.csv
Labels: 2: Dev Review

#1515 Add dim for customers, adjust the subscription history fact
  transform/mattermost-analytics/models/marts/sales/_sales__models.yml
  transform/mattermost-analytics/models/marts/sales/dim_self_serve_customers.sql
  transform/mattermost-analytics/models/marts/sales/fct_subscription_history.sql
  transform/mattermost-analytics/models/staging/cws/stg_cws__subscription_history.sql
Labels: 3: Reviews Complete

#1521 Adjust fct_subscription_history join and other fields
  transform/mattermost-analytics/models/marts/sales/fct_subscription_history.sql
  transform/mattermost-analytics/models/staging/stripe/stg_stripe__subscriptions.sql
Labels: 2: Dev Review
