Repository mattermost/mattermost-data-warehouse, pull requests merged in 2024-07, with the labels that each got.

#1546 MM-57773 Add server ids to list of test servers.
  transform/mattermost-analytics/seeds/servers/excludable_servers.csv
Labels: 2: Dev Review

#1547 MM-57542: add calls feature tracking
  transform/mattermost-analytics/dbt_project.yml
  transform/mattermost-analytics/models/intermediate/product/features/calls/int_calls_daily_usage_per_user.sql
  transform/mattermost-analytics/models/intermediate/product/features/int_daily_usage_per_user_full.sql
  transform/mattermost-analytics/models/marts/product/features/_product__features__models.yml
  transform/mattermost-analytics/models/staging/mm_calls_test_go/_mm_calls_test_go__models.yml
  transform/mattermost-analytics/models/staging/mm_calls_test_go/base/base_mm_calls_test_go__tracks.sql
  transform/mattermost-analytics/models/staging/mm_calls_test_go/stg_mm_calls_test_go__tracks.sql
Labels: 2: Dev Review

#1545 Update version_release_dates.csv
  transform/snowflake-dbt/seeds/version_release_dates.csv
Labels: 2: Dev Review, Do Not Merge

#1556 MM-59394: add copilot feature usage
  transform/mattermost-analytics/models/intermediate/product/features/copilot/int_copilot_daily_usage_per_user.sql
  transform/mattermost-analytics/models/intermediate/product/features/int_daily_usage_per_user_full.sql
  transform/mattermost-analytics/models/marts/product/features/_product__features__models.yml
  transform/mattermost-analytics/models/staging/copilot/_copilot__docs.md
  transform/mattermost-analytics/models/staging/copilot/_copilot__models.yml
  transform/mattermost-analytics/models/staging/copilot/_copilot__sources.yml
  transform/mattermost-analytics/models/staging/copilot/base/base_copilot__tracks.sql
  transform/mattermost-analytics/models/staging/copilot/stg_copilot__tracks.sql
Labels: 3: Reviews Complete

#1561 Chore: add license dimension to active servers
  transform/mattermost-analytics/models/intermediate/product/licenses/_daily_licenses/int_server_license_daily.sql
  transform/mattermost-analytics/models/marts/product/_product__models.yml
  transform/mattermost-analytics/models/marts/product/dim_daily_license.sql
  transform/mattermost-analytics/models/marts/product/fct_active_servers.sql
Labels: 2: Dev Review
